name: 'AWS SSM parameters to environment variables'
description: 'load AWS SSM Parameters into environment variables'
author: 'Kevin Brown <kevin.brown@exogee.com>'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  application-name:
    description: 'Used as the root for the SSM lookup'
    required: true
  decryption:
    description: 'Whether the parameter must be decrypted or not.'
    required: false
    default: false
  mask-values:
    description: 'Whether to mark the results as secrets so they get masked in log output.'
    required: false
    default: true
runs:
  using: 'node16'
  main: 'index.js'
